
export const SET_CARTS='SET_CARTS'
export const SET_MODALOPEN='SET_MODALOPEN'
export const CAL_TOATOLPRICE='CAL_TOATOLPRICE'
export const SET_SHOWCOUPONBUY='SET_SHOWCOUPONBUY'
export const SET_COUPONBUYFILTER='SET_COUPONBUYFILTER'
export const SET_COUPONS='SET_COUPONS';
export const SET_CANTUANPRICE='SET_CANTUANPRICE';
